version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    ports:
      - "8000:8000"
    env_file:
      - ./docker.env
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - ./docker.env
    environment:
      MYSQL_ROOT_PASSWORD: a90f4beccbfcb567812eb08c292
      MYSQL_DATABASE: movie_catalog
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    env_file:
      - ./docker.env
    ports:
      - "8080:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
    ports:
      - "3000:80"
    environment:
      - VUE_APP_BACKEND_URL=http://laravel-app:8000

volumes:
  dbdata:
